//PINs table//
#ifndef PINTABLE
#define PINTABLE

#define LEFT_ENC_PIN_A 2
#define LEFT_ENC_PIN_B 20
#define RIGHT_ENC_PIN_A 3
#define RIGHT_ENC_PIN_B 21
#define RIGHT_MOTOR_BACKWARD 10
#define LEFT_MOTOR_BACKWARD  9
#define RIGHT_MOTOR_FORWARD  11
#define LEFT_MOTOR_FORWARD   8

#endif